### ISSUE TITLE
Error "fatal: remote mirror already exists."

### ISSUE THREAD

**Issue by electroma** [pixta-dev/repository-mirroring-action#11]
Not sure what's going on, but it looks like the action uses hardcoded remote name.
And somehow remote is preserved between action executions on self-hosted runners.

The first time action runs just fine, but the next time it runs on the same runner node - it fails with  "fatal: remote mirror already exists."

The setup is pretty basic:
```
name: Mirror to XXX
on:
  push:
    branches:
      - master
jobs:
  mirror-it:
    runs-on: self-hosted
    steps:                        
      - uses: actions/checkout@v2
        with:
          persist-credentials:
            false
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:xxx/clone.git
          ssh_private_key:     
            ${{ secrets.MIRROR_PRIVATE_KEY }}

```
