### ISSUE TITLE
Getting fatal: remote mirror already exists. error when mirroring 

### ISSUE THREAD

**Issue by alessandro-mariotti-zupit** [pixta-dev/repository-mirroring-action#17]
I'm getting a 
```
fatal: remote mirror already exists.
```
error when mirroring.

I'm using self-hosted github runners.

![image](https://user-images.githubusercontent.com/114984852/201347533-16d7a251-6024-4ad3-ac4a-8fe12d0a9f12.png)

My action is:
```
name: Mirroring

on:
  push:
    branches: [ "main", "release/*" ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  delete:
    branches: [ "main", "release/*" ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  to_gitlab:
    runs-on: ['pinga', 'pipeline', 'native']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            a-very-nice-private-repo
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}

```

I've tried adding:
```      
- run: git remote remove mirror || true
```

after the checkout phase but I get permission errors because the pixta-dev/repository-mirroring-action runs as Docker, which has different permissions on file system.
