### ISSUE TITLE
v1.1.1 doesn't support neither actions/checkout@v3.3.0 nor actions/checkout@v3

### ISSUE THREAD

**Issue by fscarmen** [pixta-dev/repository-mirroring-action#24]
Your repo is very usefully. 
We expect you can modify the program to support [actions/checkout@v3.3.0].
Thank you!

**Comment by yasaichi** [comment]
@fscarmen 
We tried to reproduce a bug (?) on #25, but couldn't. Will you please tell us more detail?

**Comment by fscarmen** [comment]
It 's ok when the checkout is v1

```
name: 'GitHub Actions Mirror'

on:
  workflow_dispatch:
#  push:
#    branches: 
#      - master
  schedule:
    - cron: '20 20 * * *'

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:fscarmen/warp_unlock.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}

  mirror_to_bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to bitbucket'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@bitbucket.org:fscarmen/warp_unlock.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}

  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitee.com:fscarmen/warp_unlock.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}
```

![image](https://user-images.githubusercontent.com/62703343/212377342-7a50ab35-8a9d-4926-8ded-d77f1687fc8a.png)

===========================================================================
When i updated the actions/checkout@v1 to actions/checkout@v3.3.0 and pixta-dev/repository-mirroring-action@v1 to pixta-
dev/repository-mirroring-action@v1.1.1.  The actions run fail.
```
name: 'GitHub Actions Mirror'

on:
  workflow_dispatch:
#  push:
#    branches: 
#      - master
  schedule:
    - cron: '20 20 * * *'

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.3.0
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@gitlab.com:fscarmen/warp_unlock.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}

  mirror_to_bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.3.0
      - name: 'Mirror to bitbucket'
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@bitbucket.org:fscarmen/warp_unlock.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}

  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.3.0
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@gitee.com:fscarmen/warp_unlock.git
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}
```
![image](https://user-images.githubusercontent.com/62703343/212378062-6eb2018c-05d6-4653-b5eb-d8b19dd2d70d.png)
