### ISSUE TITLE
push rejected by remote (shallow update not allowed)

### ISSUE THREAD

**Issue by Kyrela** [pixta-dev/repository-mirroring-action#27]
When trying to run the worflow that worked perfectly fine before, we ran into an error:

```
To <repo>
 ! [remote rejected] origin/master -> master (shallow update not allowed)
error: failed to push some refs to <repo>
```

I searched on stackoverflow and found that it was caused by a shallow clone. But I don't have any idea of how to fix it, I don't event know if I *can* fix it.

**Comment by Ximaz** [comment]
Any recent information about it ?

**Comment by Ximaz** [comment]
I found more info in [this](https://github.com/pixta-dev/repository-mirroring-action/issues/24#issuecomment-1382622215) issue. It would appear that specifying the ``fetch-depth: 0`` thing to ``action/checkout@3`` would do the job. Apparently, it works fine without it for checkout@1, but for 3 and 3.3.0, you may add the flag. Example :

```yml
name: repository-mirroring

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  morror-it:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: repository-mirroring-action
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url:
            git@github.com:<USER>/<REPO>.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
```
