### ISSUE TITLE
GitLab: You cannot create a branch with an invalid name.

### ISSUE THREAD

**Issue by alexey-sh** [pixta-dev/repository-mirroring-action#35]
.github/workflows/mirror.yml
```
name: Mirror to GitLab
on:
  push:
    branches: ['**']
  delete:
    branches: ['**']

jobs:
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.GITLAB_MIRROR_REPO_URL }}
          ssh_private_key: ${{ secrets.GITLAB_MIRROR_SSH_KEY }}
```

```
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /github/home/.ssh/id_rsa
debug1: Authentication succeeded (publickey).
Authenticated to gitlab.com ([172.65.251.[78](https://github.com/alexey-sh/mirror-test/actions/runs/15239211103/job/42857190687#step:4:79)]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: Sending command: git-receive-pack 'alexey__sh/mirror-test.git'
remote: GitLab: You cannot create a branch with an invalid name.
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
debug1: fd 2 clearing O_NONBLOCK
Transferred: sent 2544, received 1936 bytes, in 0.5 seconds
Bytes per second: sent 5354.6, received 4074.9
debug1: Exit status 0
To gitlab.com:alexey__sh/mirror-test.git
 ! [remote rejected] origin/main -> main (pre-receive hook declined)
 ! [remote rejected] origin/HEAD -> HEAD (pre-receive hook declined)
error: failed to push some refs to '***'
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Run pixta-dev/repository-mirroring-action@v1
```

I switched to "wearerequired/git-mirror-action@v1" which works fine out of the box.
